baseurl = "http://osrg.github.io/earthquake/"
languageCode = "en-us"
title = "Earthquake"
## NOTE: the theme has been significantly modified for Earthquake.
theme = "bootie-docs-custom"
copyright = "Copyright© 2015 Nippon Telegraph and Telephone Corporation"
[params]
  description = "A framework of implementation level distributed system model checkers"
  mainMenu = ["about", "gettingStarted", "categories/blog"]
  repositoryUrl = "https://github.com/osrg/earthquake/"
