sudo: required

services:
  - docker

# TODO: cache docker build (not yet supported on Travis?)
before_install:
  - docker build -t osrg/earthquake .

script:
  - true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3764d3d36d4961c05d54
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

