init = "init.sh"
run = "run.sh"
validate = "validate.sh"
clean = "clean.sh"
explorePolicy = "random"

notCleanIfValidationFail= "true"

[explorePolicyParam]
 minInterval = 5

# storageType = "mongodb"
